# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af6d129a9d25cedbcb94110cdc99410377b09f7180a37a9057b1fd2af389cb041d4a04dfba9e90a40301ba6b5a15888366fddf6d40e261ffc428f6c4dc5b07b0

test:
  secret_key_base: 1ab8921f2e38b51ae0eae116042bde8e70e9db3d7ea480386153e353d3feb410a74222a29e3f3c8b724fc93a41ec73ceeaabc356328f95e2439843a2118e909f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
